[package]
name = "kernel"
version = "0.1.0"
authors = ["Tim Peters <mail@darksecond.nl>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = { path = "../bootloader" }