[package]
name = "unx-build"
version = "0.1.0"
authors = ["Tim Peters <mail@darksecond.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
gpt = "2.0.0"
fatfs = "0.3.5"
anyhow = "1.0.40"